#! /bin/bash
if [$# -ge 1 ]; then
  ptn=$1
  file="*"
  dir="."
  if [ $# -ge 2 ]; then
    file="$2"
    if [ $# -ge 3 ]; then
      dir="$3"
    fi
  fi
  grep -Hn -e "$ptn" -r --include="$file" "$dir"
else
  echo "USAGE: `basename $0` pattern [file] [dir]"
fi

